#!/bin/sh

cwd=$(pwd)
dir=.dotfiles

which stow
if ! which stow; then
	printf '%s\n' "Error: GNU Stow not found, exiting..."
	exit 1;
fi

printf '%s\n' "==> Starting setup process"

printf '%s\n' "Changing to the $dir directory..."
cd "$HOME/$dir" || return
printf '%s\n' "Done."

printf '%s\n' "Running GNU Stow"
stow --verbose ./*
printf '%s\n' "Done."

printf '%s\n' "==> Setting up colours"
rm -rf "$HOME/.config/base16-shell"
git clone https://github.com/chriskempson/base16-shell.git "$HOME/.config/base16-shell/"
mkdir -p "$HOME/.vim/plugged"
cp "$HOME/.vim/colors/lightline/streamline.vim" "$HOME/.vim/plugged/lightline.vim/autoload/lightline/colorscheme/"
cp "$HOME"/.vim/plugged/base16-vim/colors/*.vim "$HOME/.vim/colors"
printf '%s\n' "Done."

printf '%s\n' "==> Setting up Neovim"
mkdir -p "$HOME/.config"
rm -f "$HOME/$dir/vim/.vim/init.vim"
rm -rf "$HOME"/.config/nvim
rm -rf "$HOME"/.local/share/nvim
rm -rf "$HOME"/.local/state/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
	~/.local/share/nvim/site/pack/packer/start/packer.nvim
printf '%s\n' "Done."

cd "$cwd" || return
printf '%s\n' "==> Finished. Please restart your shell or source your shell's config file."
