#!/bin/sh

cwd=$(pwd)
dir=.dotfiles
olddir=.dotfiles_old
files=".bashrc .bash_profile .bin .dwm .gitignore_global .screenrc .tmp .tmux.conf .vim .vimrc .xbindkeysrc .Xdefaults .xinitrc .Xresources .zshrc"

printf '%s\n' "==> Starting setup process"
printf '%s\n' "Creating $olddir for backup of any existing dotfiles in ~ ..."
mkdir -p ~/$olddir
printf '%s\n' "Done."

printf '%s\n' "Changing to the $dir directory..."
cd ~/$dir
printf '%s\n' "Done."

printf '%s\n' "Moving any existing dotfiles from ~ to $olddir"
for file in $files; do
	mv ~/$file ~/$olddir
	printf '%s\n' "Creating symlink to $file in home dir."
	ln -s ~/$dir/$file ~/$file
done

printf '%s\n' "==> Cloning Vundle"
rm -rf ~/.vim/bundle
mkdir ~/.vim/bundle && cd ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git
printf '%s\n' "Done."

printf '%s\n' "==> Installing Vundle"
vim +PluginInstall +qall
printf '%s\n' "Done."

printf '%s\n' "==> Setting up colours"
rm -rf ~/.config/base16-shell
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
ln ~/.vim/colors/lightline/streamline.vim ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/
cp ~/.vim/bundle/base16-vim/colors/*.vim ~/.vim/colors
printf '%s\n' "Done."

cd $cwd
printf '%s\n' "==> Finished. Please restart your shell or source your shell's config file."
