#!/bin/sh

cwd=$(pwd)
dir=.dotfiles

printf '%s\n' "==> Starting setup process"

printf '%s\n' "Changing to the $dir directory..."
cd ~/$dir || return
printf '%s\n' "Done."

printf '%s\n' "Running GNU Stow"
stow --verbose */
printf '%s\n' "Done."

printf '%s\n' "==> Setting up colours"
rm -rf ~/.config/base16-shell
git clone https://github.com/chriskempson/base16-shell.git "$HOME/.config/base16-shell/"
cp ~/.vim/colors/lightline/streamline.vim ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/
cp ~/.vim/bundle/base16-vim/colors/*.vim ~/.vim/colors
printf '%s\n' "Done."

printf '%s\n' "==> Setting up Neovim"
mkdir -p ~/.config
rm -f "$HOME/$dir/vim/.vim/init.vim"
rm -f "$HOME/.config/nvim"
ln -s "$HOME/$dir/vim/.vimrc" "$HOME/$dir/vim/.vim/init.vim"
ln -s "$HOME/$dir/vim/.vim" "$HOME/.config/nvim"
printf '%s\n' "Done."

cd "$cwd" || return
printf '%s\n' "==> Finished. Please restart your shell or source your shell's config file."
