#!/bin/sh
echo "==> Starting setup process"
mkdir ~/.vim/bundle && cd ~/.vim/bundle
echo "==> Cloning Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git
echo "==> Installing Vundle"
vim +PluginInstall +qall
echo "==> Setting up colours"
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
ln ~/.vim/colors/lightline/streamline.vim ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/
cp ~/.vim/bundle/base16-vim/colors/*.vim ~/.vim/colors
zsh
base16_tomorrow-night
exit
cd ~
echo "==> Done!"
