#!/bin/sh
#
xrandr --output HDMI-0 --off --output DVI-I-1 --mode 1680x1050 --rate 60.00 --pos 1920x0 --rotate normal --output DVI-I-0 --off --output DVI-I-3 --off --output DVI-I-2 --mode 1920x1080 --rate 144.00 --pos 0x0 --rotate normal
